language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"


install:
- true # use this to skip the install step or add any commands required to install your project dependencies

script:
- python test/test_1.py
- python test/test_2.py
- python test/test_list.py

 # or any other command you'd like to run your tests with
