language: python
dist: trusty
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  fast_finish: true
  include:
    - env: TOXENV=docs
    - env: TOXENV=lint-py2
    - env: TOXENV=lint-py3
    - env: TOXENV=mypy
    - env: TOXENV=packaging
    # PyPy jobs start first -- they are the slowest
    - env: TOXENV=pypy
      python: pypy
    - env: TOXENV=pypy3
      python: pypy3
    # Latest Stable CPython jobs
    - env: TOXENV=py27
      python: 2.7
    - env: TOXENV=py36
      python: 3.6
    # All the other Py3 versions
    - env: TOXENV=py33
      python: 3.3
    - env: TOXENV=py34
      python: 3.4
    - env: TOXENV=py35
      python: 3.5
    # Nightly Python goes last
    - env: TOXENV=py37
      python: nightly
  allow_failures:
    - python: nightly

install:
- true # use this to skip the install step or add any commands required to install your project dependencies

script:
- python test/test_1.py
- python test/test_2.py
- python test/test_list.py

 # or any other command you'd like to run your tests with
